version: '2'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - /home/admin/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - /home/admin/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
#      - /home/admin/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
 #     - /home/admin/server.crt:/usr/local/apache2/conf/server.crt
  #    - /home/admin/server.key:/usr/local/apache2/conf/server.key

  tomcat:
    image: tomcat:latest
    container_name: tomcat
    ports:
      - 9090:9090
    volumes:
      - /home/admin/sample.war:/usr/local/tomcat/webapps/sample.war
      - /home/admin/server.xml:/usr/local/tomcat/conf/server.xml
      - /home/admin/web.xml:/usr/local/tomcat/webapps/sample/WEB-INF/web.xml
    depends_on:
      - openldap

  openldap:
    image: bitnami/openldap:latest
    container_name: openldap
    ports:
      - 1389:389
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_USERS=juan,carlos
      - LDAP_PASSWORDS=juan123,carlos123
